name: Publish to PyPI

on:
  release:
    types: [published]

  
jobs:
  runs-on: ubuntu-latest
  publish:
    steps:
      - name: Configure poetry
        run: poetry config pypi-token.pypi "${{ secrets.PYPI_TOKEN }}"
      - name: Build and publish package
        run: poetry publish --build
  
