  
name: Test

on:
  push:
    branches:
        - master
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        poetry-version: [1.0.10]
        os: [ubuntu-18.04, macos-latest, windows-latest]
      fail-fast: false
    
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
            poetry-version: ${{ matrix.poetry-version }}
      - uses: actions/cache@v1
        with:
            path: ~/.cache/pypoetry/virtualenvs
            key: ${{ runner.os }}-{{ runner.python-version }}-{{ runner.poetry-version }}-poetry-${{ hashFiles('poetry.lock') }}
            restore-keys: |
                ${{ runner.os }}-{{ runner.python-version }}-{{ runner.poetry-version }}-poetry-
    
      - name: Install dependencies
        run: poetry install
      - name: Run tests
        run: poetry run pytest --cov starlette_session --cov-report=xml tests/    
    
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            file: ./coverage.xml
            flags: unittests
            fail_ci_if_error: true
